// import themes from 'daisyui/src/theming/themes'
import themes from 'src/styles/themes'
import daisyui from 'daisyui'

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './index.html',
        './src/**/*.{vue,js,ts,jsx,tsx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'on-secondary-fixed': 'var(--on-secondary-fixed)',
                'surface-container-lowest': 'var(--surface-container-lowest)',
                'tertiary-fixed': 'var(--tertiary-fixed)',
                'surface': 'var(--surface)',
                'primary-container': 'var(--primary-container)',
                'tertiary-container': 'var(--tertiary-container)',
                'background': 'var(--background)',
                'outline-variant': 'var(--outline-variant)',
                'on-tertiary-container': 'var(--on-tertiary-container)',
                'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
                'on-surface': 'var(--on-surface)',
                'surface-container': 'var(--surface-container)',
                'secondary-container': 'var(--secondary-container)',
                'on-primary-container': 'var(--on-primary-container)',
                'secondary': 'var(--secondary)',
                'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
                'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
                'primary-fixed': 'var(--primary-fixed)',
                'secondary-fixed': 'var(--secondary-fixed)',
                'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
                'surface-dim': 'var(--surface-dim)',
                'inverse-surface': 'var(--inverse-surface)',
                'surface-tint': 'var(--surface-tint)',
                'error-container': 'var(--error-container)',
                'on-secondary': 'var(--on-secondary)',
                'tertiary': 'var(--tertiary)',
                'error': 'var(--error)',
                'on-error-container': 'var(--on-error-container)',
                'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
                'surface-variant': 'var(--surface-variant)',
                'on-primary-fixed': 'var(--on-primary-fixed)',
                'on-primary': 'var(--on-primary)',
                'surface-container-low': 'var(--surface-container-low)',
                'outline': 'var(--outline)',
                'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
                'inverse-on-surface': 'var(--inverse-on-surface)',
                'inverse-primary': 'var(--inverse-primary)',
                'on-background': 'var(--on-background)',
                'on-surface-variant': 'var(--on-surface-variant)',
                'surface-container-highest': 'var(--surface-container-highest)',
                'on-secondary-container': 'var(--on-secondary-container)',
                'primary-fixed-dim': 'var(--primary-fixed-dim)',
                'surface-container-high': 'var(--surface-container-high)',
                'primary': 'var(--primary)',
                'on-tertiary': 'var(--on-tertiary)',
                'on-error': 'var(--on-error)',
                'surface-bright': 'var(--surface-bright)',
            },
            fontFamily: {
                headline: ['Manrope', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
        },
    },
    daisyui: {
        darkTheme: 'dark',
        themes: [
            {
                light: {
                    ...themes.light,
                    primary: '#003f87',
                    secondary: '#006877',
                    accent: '#75e7fe',
                    neutral: '#191c1d',
                    'base-100': '#ffffff',
                    'base-200': '#f3f4f5',
                    'base-300': '#e1e3e4',
                    'base-content': '#191c1d',
                },
            },
            {
                dark: {
                    ...themes.dark,
                    primary: '#3b82f6',
                    secondary: '#22d3ee',
                    accent: '#75e7fe',
                    neutral: '#0b0e14',
                    'base-100': '#0f172a',
                    'base-200': '#1e293b',
                    'base-300': '#334155',
                    'base-content': '#f1f5f9',
                },
            },
        ],
    },
    plugins: [daisyui],
}



// /** @type {import('tailwindcss').Config} */
// export default {
//     content: [
//         "./index.html",
//         "./src/**/*.{vue,js,ts,jsx,tsx}",
//     ],
//     theme: {
//         extend: {
//             colors: {
//                 "on-secondary-fixed": "#001f25",
//                 "surface-container-lowest": "#ffffff",
//                 "tertiary-fixed": "#83fc8e",
//                 "surface": "#f8f9fa",
//                 "primary-container": "#0056b3",
//                 "tertiary-container": "#006722",
//                 "background": "#f8f9fa",
//                 "outline-variant": "#c2c6d4",
//                 "on-tertiary-container": "#6fe87c",
//                 "on-primary-fixed-variant": "#004491",
//                 "on-surface": "#191c1d",
//                 "surface-container": "#edeeef",
//                 "secondary-container": "#75e7fe",
//                 "on-primary-container": "#bbd0ff",
//                 "secondary": "#006877",
//                 "on-tertiary-fixed-variant": "#00531a",
//                 "tertiary-fixed-dim": "#66df75",
//                 "primary-fixed": "#d7e2ff",
//                 "secondary-fixed": "#a4eeff",
//                 "on-secondary-fixed-variant": "#004e5a",
//                 "surface-dim": "#d9dadb",
//                 "inverse-surface": "#2e3132",
//                 "surface-tint": "#115cb9",
//                 "error-container": "#ffdad6",
//                 "on-secondary": "#ffffff",
//                 "tertiary": "#004c17",
//                 "error": "#ba1a1a",
//                 "on-error-container": "#93000a",
//                 "on-tertiary-fixed": "#002106",
//                 "surface-variant": "#e1e3e4",
//                 "on-primary-fixed": "#001a40",
//                 "on-primary": "#ffffff",
//                 "surface-container-low": "#f3f4f5",
//                 "outline": "#727784",
//                 "secondary-fixed-dim": "#62d6ed",
//                 "inverse-on-surface": "#f0f1f2",
//                 "inverse-primary": "#acc7ff",
//                 "on-background": "#191c1d",
//                 "on-surface-variant": "#424752",
//                 "surface-container-highest": "#e1e3e4",
//                 "on-secondary-container": "#006776",
//                 "primary-fixed-dim": "#acc7ff",
//                 "surface-container-high": "#e7e8e9",
//                 "primary": "#003f87",
//                 "on-tertiary": "#ffffff",
//                 "on-error": "#ffffff",
//                 "surface-bright": "#f8f9fa",
//             },
//             fontFamily: {
//                 headline: ["Manrope", "sans-serif"],
//                 body: ["Inter", "sans-serif"],
//                 label: ["Inter", "sans-serif"],
//             },
//             borderRadius: {
//                 DEFAULT: "0.125rem",
//                 lg: "0.25rem",
//                 xl: "0.5rem",
//                 full: "0.75rem",
//             },
//         },
//     },
//     daisyui: {
//         themes: [
//             {
//                 light: {
//                     ...themes["light"],
//                     primary: "#003f87",
//                     secondary: "#006877",
//                     accent: "#75e7fe",
//                     neutral: "#191c1d",
//                     "base-100": "#ffffff",
//                 },
//             },
//         ],
//     },
//     plugins: [],
// }